<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.accurids.fhir</groupId>
        <artifactId>core</artifactId>
        <version>5.1.0-patch1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>convertors</artifactId>
    <packaging>jar</packaging>

    <dependencies>

        <!-- Commons -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <optional>true</optional>
        </dependency>
        
        <!-- HAPI Dependencies -->
        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-base</artifactId>
        </dependency>
        <dependency>
            <groupId>com.accurids.fhir</groupId>
            <artifactId>utilities</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- JSON Parsers -->
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- FHIR Versions -->
        <dependency>
            <groupId>com.accurids.fhir</groupId>
            <artifactId>dstu2</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.accurids.fhir</groupId>
            <artifactId>dstu2016may</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.accurids.fhir</groupId>
            <artifactId>dstu3</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.accurids.fhir</groupId>
            <artifactId>r4</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.accurids.fhir</groupId>
            <artifactId>r5</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>
        <!-- UCUM -->
        <dependency>
            <groupId>org.fhir</groupId>
            <artifactId>ucum</artifactId>
            <version>1.0.2</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit_version}</version>
            <scope>test</scope>
        </dependency>
        <!-- JUnit Jupiter -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit_jupiter_version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>${junit_jupiter_version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.basepom.maven</groupId>
                <artifactId>duplicate-finder-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
